### ISSUE TITLE
style Home component/ page

### ISSUE THREAD

**Issue by elsa-brown** [space-chat/space-chat#35]

**Comment by elsa-brown** [comment]
this is done but two of the things aren't centered and I figure someone tmrw will kno how to do it

**Comment by thefishter** [comment]
lol it just needs a css file! we can use flexbox to take care of those manual `<br>`s. and to import a sweet google font super quickly...

in index.html:
`<link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=[SELECTED_FONT_HERE]">`

and then you can use `{ font-family: [SELECTED_FONT_HERE]; }` in the css file
