### ISSUE TITLE
avatars appear for each user in circle on plane

### ISSUE THREAD

**Issue by Keziyah** [space-chat/space-chat#52]

**Comment by Keziyah** [comment]
See this: http://psitsmike.com/2011/10/node-js-and-socket-io-multiroom-chat-tutorial/

**Comment by thefishter** [comment]
https://socket.io/docs/rooms-and-namespaces/

**Comment by elsa-brown** [comment]
Prev "users can talk in different rooms"
- transferred to other issues, but I'm leaving this here for the notes in case
