### ISSUE TITLE
Knots: render avatars in scene

### ISSUE THREAD

**Issue by Keziyah** [space-chat/space-chat#68]

**Comment by Keziyah** [comment]
https://threejs.org/docs/index.html#manual/introduction/WebGL-compatibility-check

**Comment by thefishter** [comment]
honestly this is probably not necessary, given that our react-speech-recognition/ web speech api usage means this will only work in chrome anyway: https://www.npmjs.com/package/react-speech-recognition

plus: "Chrome, Firefox, Internet Explorer, Opera, and Safari are all known to have good WebGL support on both desktop and mobile browsers"

...literally what else would we want to support
